import { RedisClientType } from '@redis/client'
import { KpiResult, NetworkId } from '../../../types'
import { getBlockRange } from '../utils/events'
import { fetchNetworkMetrics } from '../utils/networks'

/**
 * Calculates gas usage for Lisk infrastructure activity.
 *
 * **KPI Unit**: Gas units (computational units consumed)
 *
 * **Business Purpose**: Measures the computational resources (gas) consumed by a specific user's
 * transactions on Lisk network. This metric quantifies the infrastructure utilization generated by user
 * interactions and supports gas usage analysis for network sustainability and resource allocation.
 *
 * **Protocol Context**: Lisk tracks gas consumption to measure network utilization
 * and infrastructure impact. Gas usage serves as a proxy for computational resource consumption and
 * network contribution, supporting infrastructure funding decisions and network optimization.
 *
 * **Network**: Lisk Mainnet
 *
 * **Data Sources**:
 * - **HyperSync**: Transaction and gas usage data from Lisk network via HyperSync client
 * - **Block Data**: Timestamps via `getBlockRange` utility for temporal filtering
 *
 * **Business Assumptions**:
 * - Gas usage accurately represents computational resource consumption
 * - User's infrastructure impact is proportional to total gas consumed within time window
 * - All transaction types contribute equally to network utilization regardless of purpose
 * - Gas measurements include both successful and failed transaction attempts
 * - Infrastructure funding allocation can be based on proportional gas contribution
 *
 * **Gas Types**: Transaction execution gas, contract interaction gas, token transfer gas, and smart contract deployment gas
 *
 * **Calculation Method**:
 * 1. Queries all transactions initiated by user wallet within the specified time window
 * 2. Retrieves transaction receipts to extract gas used for each transaction
 * 3. Filters transactions by block timestamp to ensure they fall within the time range
 * 4. Aggregates total gas consumed across all user transactions
 * 5. Returns total gas usage representing user's infrastructure utilization
 *
 * @param params - Calculation parameters
 * @param params.address - User wallet address to calculate gas usage for
 * @param params.startTimestamp - Start of time window for gas calculation (inclusive)
 * @param params.endTimestampExclusive - End of time window for gas calculation (exclusive)
 *
 * @returns Promise resolving to total gas units consumed by user's transactions
 */
export async function calculateKpi({
  address,
  startTimestamp,
  endTimestampExclusive,
  redis,
}: {
  address: string
  startTimestamp: Date
  endTimestampExclusive: Date
  redis?: RedisClientType
}): Promise<KpiResult> {
  const { startBlock, endBlockExclusive } = await getBlockRange({
    networkId: NetworkId['lisk-mainnet'],
    startTimestamp,
    endTimestampExclusive,
    redis,
  })

  const { totalGasUsed: kpi, totalTransactions } = await fetchNetworkMetrics({
    networkId: NetworkId['lisk-mainnet'],
    users: [address],
    startBlock,
    endBlockExclusive,
  })
  return { kpi, metadata: { totalTransactions } }
}
